### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by ashoktimsina** [jakobherpich/pyICs#1]
hi, 
When I wrote in the comment line 
"python setup.py install", I faced the following issue.
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import pyICs
  File "/home/ashok/pyICs/pyICs/__init__.py", line 20, in <module>
    from . import am_profiles, density_profiles, equilibrium_halos, tools
  File "/home/ashok/pyICs/pyICs/equilibrium_halos.py", line 152
    raise RuntimeError, "Mass array not monotonically increasing"
                      ^
SyntaxError: invalid syntax

how can I overcome this issue?
Ashok

**Comment by jakobherpich** [comment]
I assume, you installed `pyICs` with `python3`. The code has been written in `python2.7` syntax, which is partly incompatible with `python3`. Until the code is ported to `python3`, you'll have to install and use it with `python2.7`. I won't be able to do this before mid-May. I'm sorry for the inconvenience.

**Comment by jakobherpich** [comment]
Issue fixed with the latest commit. @ashoktimsina, can you please confirm?
